/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DhtmlxGantt: typeof import('./src/components/DhtmlxGantt.vue')['default']
    FrappeGantt: typeof import('./src/components/FrappeGantt.vue')['default']
    GanttElastic: typeof import('./src/components/GanttElastic.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
  }
}
